name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    name: Testing CodeEdit
    runs-on: [self-hosted, macOS]
    steps:
      - name: Testing App
        run: exec ./.github/scripts/test_app.sh arm
